<table border=0 cellspacing=2 cellpadding=2 width="100%">
            <tbody>
              <tr>
                <td rowspan=2 width="30%" align=center><a href='[field:arcurl/]'><img src='[field:litpic function='thumb(@me,120,120)'/]' border='0' width='120' height='120' alt='[field:title/]'></a></td>
                <td width="70%"><a href="[field:arcurl/]">[field:title/]</a></td>
              </tr>
              <tr>
                <td>[field:description/]...</td>
              </tr>
            </tbody>
          </table>