<div class="item">
        <dl>
          <dt><a target="_blank" href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:title/]" width="280px" /></a></dt>
          <dd class="case_name"><a target="_blank" href="[field:arcurl/]">[field:title/]</a></dd>
          <dd class="case_tag"><a href='[field:typeurl/]'>[field:typename/]</a></dd>
          <dd class="case_int"><a target="_blank" href="[field:arcurl/]">[field:description/]......</a></dd>
        </dl>
      </div>