<?php
$z[0]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",162,260);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",281,379);
$z[1][4]['typeid']="2";
$z[2]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",400,499);
$z[2][4]['typeid']="22";
$z[3]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",576,674);
$z[3][4]['typeid']="3";
$z[4]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",695,793);
$z[4][4]['typeid']="7";
$z[5]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",814,913);
$z[5][4]['typeid']="11";
$z[6]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",990,1089);
$z[6][4]['typeid']="16";
$z[7]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",1110,1209);
$z[7][4]['typeid']="17";
$z[8]=Array("type","<A href=\"[field:typelink/]\" rel=\"nofollow\">[field:typename/]</A>",1230,1329);
$z[8][4]['typeid']="18";
$z[9]=Array("global","",1469,1501);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1694,1726);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",1843,1875);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",1970,2002);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",3396,3428);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("global","",3626,3652);
$z[14][4]['name']="cfg_powerby";
$z[15]=Array("global","",3664,3688);
$z[15][4]['name']="cfg_beian";

?>