<?php
$z[0]=Array("global","",142,174);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",309,341);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",544,576);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channel","\r\n              <li><a id=menu3 href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              ",784,1035);
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a id=menu2 href='~typelink~' class='a1'>~typename~</a></li>";

?>